### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by thoiruddin** [Aybaaan/inventory-management-system#1]
May I know where to get UC folder and the files contained inside? And also the files inside Properties needed.

**Comment by IvanVeluz18** [comment]
missing files were uploaded. let me know if there are errors or other problems

**Comment by thoiruddin** [comment]
Hi,

Thanks for the update. Can you share the database too? Inside this folder?

C:\Users\Ivan\Documents\InventoryDB.mdf

I want to learn or refresh back my skill for Primary Key.
